---
title: Boleto Simples Features
timezone: America/Sao_Paulo
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
permalink: pretty
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-assets
include:
- _headers
assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  gzip: true
  defaults:
    js: { integrity: true } # true on JEKYLL_ENV=production
    css: { integrity: true } # true on JEKYLL_ENV=production
    img: { integrity: true } # true on JEKYLL_ENV=production
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  sources:
    - assets
    - css
    - uploads
    - js
    - _sass
    - fonts

