---
title: Boleto Simples Features
timezone: America/Sao_Paulo
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
permalink: pretty
gems:
- jekyll-feed
- jekyll-sitemap
